dist: trusty
language: python

python:
  - "2.7"

env:
  global:
    # !!! Replace the encryption label below with YOURS
    - ENCRYPTION_LABEL: "c700222d5325"
    # !!! Replace the email below with YOURS
    - COMMIT_AUTHOR_EMAIL: "misterjbee@gmail.com"

script:
  - bash .github/build.sh

branches:
  only:
    - master
    # Add more branches if required
